"""Card generator for WikiBattle.

Fetches Wikipedia articles, classifies them, and builds card objects.
Handles deck generation with proper type distribution.
"""

import random
import uuid
from typing import Optional
from wikipedia_api import (
    fetch_random_articles,
    fetch_articles_with_coordinates,
    classify_article,
)


def _make_card_id() -> str:
    return str(uuid.uuid4())[:8]


def build_card_from_article(article: dict, card_type: Optional[str] = None) -> dict:
    """Build a card dict from a Wikipedia article.

    The card starts without effects - those are generated by AI when drawn.
    """
    if card_type is None:
        card_type = classify_article(article)

    card = {
        "id": _make_card_id(),
        "name": article["title"],
        "card_type": card_type,
        "image": article.get("thumbnail"),
        "wiki_url": article.get("url", ""),
        "extract": article.get("extract", ""),
        "categories": article.get("categories", []),
        "coordinates": article.get("coordinates"),
        # Effects will be filled in by AI when the card is drawn
        "effects_generated": False,
        "effect_description": "",
        "effects": [],
    }

    if card_type == "creature":
        # Base stats will be set by AI, but provide defaults
        card["attack"] = 1
        card["health"] = 1
        card["max_health"] = 1
        card["mana_cost"] = 1
        card["abilities"] = []
        card["can_attack"] = False  # Summoning sickness
        card["is_tapped"] = False

    elif card_type == "terrain":
        card["mana_cost"] = 0  # Terrains are free to play
        card["mana_production"] = 1  # Base: produces 1 mana
        card["is_tapped"] = False
        if article.get("coordinates"):
            card["coordinates"] = article["coordinates"]

    elif card_type == "spell":
        card["mana_cost"] = 1  # Will be overridden by AI

    return card


def generate_deck(target_size: int = 20) -> list[dict]:
    """Generate a random deck of cards from Wikipedia.

    Aims for roughly: 8 terrains, 8 creatures, 4 spells.
    """
    # Target distribution
    target_terrains = 8
    target_creatures = 8
    target_spells = 4

    terrains = []
    creatures = []
    spells = []

    # First, fetch articles with coordinates for guaranteed terrains
    geo_articles = fetch_articles_with_coordinates(count=target_terrains + 4)
    for article in geo_articles:
        if len(terrains) >= target_terrains:
            break
        card = build_card_from_article(article, card_type="terrain")
        terrains.append(card)

    # Fetch random articles for creatures and spells
    random_articles = fetch_random_articles(count=40)
    for article in random_articles:
        card_type = classify_article(article)

        if card_type == "creature" and len(creatures) < target_creatures:
            creatures.append(build_card_from_article(article, "creature"))
        elif card_type == "spell" and len(spells) < target_spells:
            spells.append(build_card_from_article(article, "spell"))
        elif card_type == "terrain" and len(terrains) < target_terrains:
            terrains.append(build_card_from_article(article, "terrain"))

    # Fill gaps if we didn't get enough of a type
    # Use remaining random articles
    remaining = [a for a in random_articles if not any(
        c["name"] == a["title"] for c in terrains + creatures + spells
    )]

    while len(creatures) < target_creatures and remaining:
        article = remaining.pop(0)
        creatures.append(build_card_from_article(article, "creature"))

    while len(spells) < target_spells and remaining:
        article = remaining.pop(0)
        spells.append(build_card_from_article(article, "spell"))

    # If we still don't have enough terrains, force some random articles as terrains
    while len(terrains) < target_terrains and remaining:
        article = remaining.pop(0)
        terrains.append(build_card_from_article(article, "terrain"))

    # Combine and shuffle
    deck = terrains + creatures + spells
    random.shuffle(deck)

    # Trim or pad to target size
    deck = deck[:target_size]

    return deck


def card_to_client_view(card: dict, reveal: bool = True) -> dict:
    """Convert a card to a client-safe view.

    If reveal=False, only show card back (used for opponent's hand).
    """
    if not reveal:
        return {
            "id": card["id"],
            "hidden": True,
        }

    view = {
        "id": card["id"],
        "name": card["name"],
        "card_type": card["card_type"],
        "image": card["image"],
        "wiki_url": card["wiki_url"],
        "extract": card["extract"],
        "effect_description": card.get("effect_description", ""),
        "effects_generated": card.get("effects_generated", False),
        "mana_cost": card.get("mana_cost", 0),
        "hidden": False,
    }

    if card["card_type"] == "creature":
        view["attack"] = card.get("attack", 1)
        view["health"] = card.get("health", 1)
        view["max_health"] = card.get("max_health", 1)
        view["abilities"] = card.get("abilities", [])
        view["can_attack"] = card.get("can_attack", False)
        view["is_tapped"] = card.get("is_tapped", False)
        view["shield"] = card.get("shield", 0)
        view["frozen_turns"] = card.get("frozen_turns", 0)
        view["has_taunt"] = card.get("has_taunt", False)

    elif card["card_type"] == "terrain":
        view["mana_production"] = card.get("mana_production", 1)
        view["is_tapped"] = card.get("is_tapped", False)
        view["coordinates"] = card.get("coordinates")

    # Include effects so the client can check targeting requirements
    if card.get("effects_generated"):
        view["effects"] = card.get("effects", [])

    return view
